name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up py3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install tox
      run: pip install tox

    - name: Flake8
      run: tox -e flake8

    - name: Black
      run: tox -e black

    - name: Typing
      run: tox -e typing

  tests:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up py${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox
      run: pip install tox

    - name: Run tests
      run: tox -e py

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)

  tests-py35-pinned:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up py35
      uses: actions/setup-python@v2
      with:
        python-version: 3.5

    - name: Install tox
      run: pip install tox

    - name: Run tests
      run: tox -e py35-pinned

    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
